# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'CustomTransitionAnimationDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'EasyTransitions'

  # Pods for CustomTransitionAnimationDemo

  target 'CustomTransitionAnimationDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomTransitionAnimationDemoUITests' do
    # Pods for testing
  end

end
